SELECT 
    `idea`.`id`,
    `idea`.`user_id`,
    `idea`.`name`,
    `idea`.`pitch`,
	`idea`.`members`,
	`idea`.`skills`,
	`idea`.`space_id`,
	`idea`.`created_at` AS `createdAt`,
	`idea`.`updated_at` AS `updatedAt`,
	`interests`.`idea_id` AS `interests.idea_id`,
	`interests`.`details` AS `interests.details`,
	`interests`.`status` AS `interests.status`,
	`interests`.`user_id` AS `interests.user_id`,
	`interests->user`.`id` AS `interests.user.id`,
	`interests->user`.`name` AS `interests.user.name`,
	`interests->user`.`email` AS `interests.user.email`,
	`interests->user`.`password` AS `interests.user.password`,
	`interests->user`.`created_at` AS `interests.user.createdAt`,
	`interests->user`.`updated_at` AS `interests.user.updatedAt`,
	`myInterest`.`idea_id` AS `myInterest.idea_id`,
	`myInterest`.`user_id` AS `myInterest.user_id`,
	`myInterest`.`status` AS `myInterest.status`,
	`creator`.`id` AS `creator.id`,
	`creator`.`name` AS `creator.name`,
	`creator`.`email` AS `creator.email`,
	`creator`.`password` AS `creator.password`,
	`creator`.`created_at` AS `creator.createdAt`,
	`creator`.`updated_at` AS `creator.updatedAt`,
	`upvoter`.`id` AS `upvoter.id`,
	`upvoter`.`name` AS `upvoter.name`,
	`upvoter`.`email` AS `upvoter.email`,
	`upvoter`.`password` AS `upvoter.password`,
	`upvoter`.`created_at` AS `upvoter.createdAt`,
	`upvoter`.`updated_at` AS `upvoter.updatedAt`,
	`upvoter->idea_upvote`.`created_at` AS `upvoter.idea_upvote.createdAt`,
	`upvoter->idea_upvote`.`updated_at` AS `upvoter.idea_upvote.updatedAt`,
	`upvoter->idea_upvote`.`idea_id` AS `upvoter.idea_upvote.idea_id`,
	`upvoter->idea_upvote`.`user_id` AS `upvoter.idea_upvote.user_id`,
	`resources`.`id` AS `resources.id`,
	`resources`.`name` AS `resources.name`,
	`resources`.`content` AS `resources.content`,
	`resources`.`type` AS `resources.type`,
	`resources`.`created_at` AS `resources.createdAt`,
	`resources`.`updated_at` AS `resources.updatedAt`,
	`resources`.`idea_id` AS `resources.idea_id`
FROM `idea` AS `idea`
LEFT OUTER JOIN `interest` AS `interests` ON `idea`.`id` = `interests`.`idea_id` AND ((SELECT COUNT(*) from interest i2 WHERE status = "approved" AND user_id = interests.user_id AND idea_id IN (SELECT id FROM idea i2 WHERE space_id = idea.space_id AND id <> idea.id)) < 1) LEFT OUTER JOIN `user` AS `interests->user` ON `interests`.`user_id` = `interests->user`.`id` LEFT OUTER JOIN `interest` AS `myInterest` ON `idea`.`id` = `myInterest`.`idea_id` AND `myInterest`.`user_id` = 1 LEFT OUTER JOIN `user` AS `creator` ON `idea`.`user_id` = `creator`.`id` LEFT OUTER JOIN ( `idea_upvote` AS `upvoter->idea_upvote` INNER JOIN `user` AS `upvoter` ON `upvoter`.`id` = `upvoter->idea_upvote`.`user_id`) ON `idea`.`id` = `upvoter->idea_upvote`.`idea_id` LEFT OUTER JOIN `resource` AS `resources` ON `idea`.`id` = `resources`.`idea_id` WHERE `idea`.`id` = '1';
Executing (default): SELECT `id`, `user_id`, `idea_id`, `comment`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `comment` AS `comment` WHERE `comment`.`idea_id` = 1;